server:
  port: 58081
  servlet:
    context-path: "/data-control-manager"
spring:
  application:
    name: teros-data-control-manager
  devtools:
    livereload:
      enabled: true
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
# extra option
extra:
  env:
    teros_home: e:/teros_home